export let introText = `Every passing day, society becomes more and more integrated with social media. New communication technologies such as Facebook, Instagram, and Snapchat have become widespread and common, playing off people's addiction to validation and attention. NEWLINE It's wrong. We need to stop. And I'll show you why.`;
export const introTitle = `Technology is hurting us`;

export let negTextLevel1 = `In that case, listen to this. In 2017 alone, 94% of Americans owned phones, and looking at Americans aged 17-29, that number rose to 100%. We grow anxious without our technological companions, and on average we use them for over 4 and 1/2 hours per day! NEWLINE Let that sink in. NEWLINE 4 and 1/2 hours. We use our phones and social media daily, and we are spending so much of our precious time, so much of our precious lives, on something so inanimate and replaceable`;
export let posTextLevel1 = `It's good that you agree, but it's also important to understand why our phones and social media are hurting us. In 2017 alone, 94% of Americans owned phones, and looking at the youth population, that number rose to 100%. We grow anxious without our technological companions, and on average we use them for over 4 and 1/2 hours per day! We use our phones and social media daily, and we are spending so much of our precious time, so much of our precious lives, on something so inanimate and replaceable`;
export const textLevel1Neutral = `We are addicted to our phones`;

export let posTextLevel2 = 'Overuse of our phones and social media is destructive: a study by University of Virginia researchers Grace Chou and Nicholas Edge found that people who used social media more were unhappier with their lives and believed life was not fair. This implies that all this time spent on our phones and social media can seriously affect how we perceive the world. We cannot underestimate the effects modern communication technology has on our minds.';
export let negTextLevel2 = `That's fair, so here is some evidence that overusing social media and our phones is destructive. A study by University of Virginia researchers Grace Chou and Nicholas Edge found that people who used social media more were unhappier with their lives and believed life was not fair. NEWLINE This implies that all this time spent on our phones and social media can seriously affect how we perceive the world. We cannot underestimate the effects modern communication technology has on our minds.`;
export const textLevel2Neutral = 'Our phones depress us, they change us';

export let negTextLevel3 = `If you still don't believe me, know that many others have felt the isolation and suffering that obsessing over social media creates. Sophie Reynolds, a student at UC San Diego, struggled to find her 'group', so she fell into the trap of using social media for attention and relationships. NEWLINE She soon found herself miserable and keeping up a facade, and just like Chou and Edge observed, she was depressed about her life. NEWLINE Even if you have never experienced something like this... NEWLINE Feeling sad when our friends post their happy memories without us... NEWLINE Feeling alone when we try to substitute instant messaging for talking... NEWLINE It's natural, and social media brings all those painful emotions out.`
export let posTextLevel3 = `It's depressing, really. NEWLINE Our phones have so much control over us, and even though we understand how they can destroy us, we cannot help but use them. NEWLINE It's insidious; we want to connect with others, we want to be in the company of others, and our phones give us an easy drug for our social natures, and we continue to take those pills until we break. NEWLINE But the worst part is, depressing us is not the only thing our phones do; it's scary.`;
export const textLevel3Pos = 'A self-harming drug';
export const textLevel3Neg = `It's common: Phones hurt us all`;

